# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Akma
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Akma Comércio de Gases e Equipamentos Hospitalares
address_line: Rua Elpídio Batista Neri s/n, em São Cristovão
telephone_number: (79) 996380087
fax_number: (79) 988413272
company_email: akmaequipamentos@gmail.com
google_map: https://www.google.com/maps/place/R.+Elp%C3%ADdio+Batista+Neri+-+Rosa+Elze,+S%C3%A3o+Crist%C3%B3v%C3%A3o+-+SE,+49100-000/@-10.9248046,-37.1109214,17z/data=!3m1!4b1!4m5!3m4!1s0x71ab26924ad67d9:0xbc81ea3e6386e9cd!8m2!3d-10.9248046!4d-37.1087327

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
