title: Akma
email: akmaequipamentos@gmail.com
description: Akma site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Akma Comércio de Gases e Equipamentos Hospitalares
address_line: Rua Elpídio Batista Neri s/n, em São Cristovão
telephone_number: (79) 996380087
fax_number: (79) 988413272
company_email: akmaequipamentos@gmail.com
google_map: https://www.google.com/maps/place/R.+Elp%C3%ADdio+Batista+Neri+-+Rosa+Elze,+S%C3%A3o+Crist%C3%B3v%C3%A3o+-+SE,+49100-000/@-10.9248046,-37.1109214,17z/data=!3m1!4b1!4m5!3m4!1s0x71ab26924ad67d9:0xbc81ea3e6386e9cd!8m2!3d-10.9248046!4d-37.1087327

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
